### ISSUE TITLE
Oculus Quest support

### ISSUE THREAD

**Issue by fight4dream** [bhaptics/haptic-library#67]
We have already developed Unity games using a few products including vest, wrist, gloves. 
As oculus quest is available now, what steps are needed to get it work on Oculus Quest?

**Comment by westside** [comment]
Here's the link for [Oculus Go Guide](https://docs.google.com/document/d/1PBzxZflfX13M1jMSf0tNDkjF1mSgmRq2pGkfbgWcdDg/edit?usp=sharing)

1. Technically, Oculus Quest will be the same as Oculus Go because both are android devices.
We haven't tested quest yet (our quest did not come yet), we will let you know after testing.  

2. There will be minor update on Android SDK, so please use this after next update. 

If you have other question, please let me know.

**Comment by fight4dream** [comment]
We would like to request keys for bHaptics Player app. 

Do we have to get a key for each Device or just one can be redeemed on multiple devices?

Ethan
FIGHT4DREAM

**Comment by westside** [comment]
Sorry for late response, I've updated guide for Oculus go and there is a link for oculus go app.
Please use latest sdk [(1.4.5)](https://github.com/bhaptics/haptic-library/releases/tag/tac-1.4.5)
